version: '3.8'

name: homo-app

services:
  # ============ FRONTEND HOMOLOGAÇÃO ============
  frontend:
    image: ghcr.io/univesp-pi-2/frontend:homo-latest
    container_name: homo-front-app
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
    networks:
      - homo-network-app
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      - backend

  # ============ BACKEND HOMOLOGAÇÃO ============
  backend:
    image: ghcr.io/univesp-pi-2/backend:homo-latest
    container_name: homo-back-app
    restart: unless-stopped
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
      - DEBUG=${DEBUG:-true}
      - DB_URI=${DB_URI}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_PORT=27017
      - DATABASE=${DATABASE}
      - JWT_SECRET=${JWT_SECRET}
      - HEADER_START=${HEADER_START}
      - APP_PORT=3000
    depends_on:
      - db
    networks:
      - homo-network-app
      - proxy-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # ============ MONGODB HOMOLOGAÇÃO ============
  db:
    image: mongo:latest
    container_name: homo-back-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASS}
      MONGO_INITDB_DATABASE: ${DATABASE}
    volumes:
      - homo-mongo-data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - homo-network-app
      - proxy-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  homo-network-app:
    external: true
  proxy-network:
    external: true

volumes:
  homo-mongo-data:
    external: true
